apiVersion: v1
kind: Secret
metadata:
  name: careerhub-secret
  namespace: careerhub
type: Opaque
stringData:
  POSTGRES_USER: "app"
  POSTGRES_PASSWORD: "app"

  RABBITMQ_DEFAULT_USER: "app"
  RABBITMQ_DEFAULT_PASS: "app"

  MAIL_PASS: "ycyhqekxnqajfnxh"

  JWT_SECRET: "Yy8k2QJb4V7tRkZ1mP9hS3fX6cD0nW2aL8eT4uI9rC5oB7pM1xG6zH0vN3qJ5d"
  JWT_ISSUER: "careerhub-backend"
