server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
  port: 8081

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://postgres:5432/careerhub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  app:
    platform:
      base-url: http://localhost:3000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    listener:
      type: simple
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 50
        acknowledge-mode: auto
        default-requeue-rejected: false
    template:
      mandatory: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "when_authorized"


auth:
  jwt:
    secret: "Yy8k2QJb4V7tRkZ1mP9hS3fX6cD0nW2aL8eT4uI9rC5oB7pM1xG6zH0vN3qJ5d"
    issuer: "careerhub-backend"
    access-minutes: 60
    refresh-days: 7

jobs:
  ingest:
    exchange: ingest.jobs
    routing:
      urls: job-url
    queue:
      urls: ingest.jobs.url
    source-default: JUSTJOIN

events:
  meetup:
    groups:
      - warsawjs
      - pykonik
      - wrocnet

ingest:
  scheduler:
    enabled: true
    initial-delay: PT3M
    fixed-delay: PT12H
    sources:
      - source: JUSTJOIN
        sitemap: https://justjoin.it/sitemaps/active-jobs/part0.xml
logging:
  level:
    root: INFO

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
