server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
  port: 8081

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://postgres:5432/careerhub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  app:
    platform:
      base-url: https://careerhub-it.com
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    listener:
      type: simple
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 50
        acknowledge-mode: auto
        default-requeue-rejected: false
    template:
      mandatory: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "when_authorized"

auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:careerhub-backend}
    access-minutes: ${JWT_ACCESS_MINUTES:60}
    refresh-days: ${JWT_REFRESH_DAYS:7}

jobs:
  ingest:
    exchange: ingest.jobs
    routing:
      urls: job-url
      externalOffers: external-offer
    queue:
      urls: ingest.jobs.url
      externalOffers: ingest.jobs.external-offers
    source-default: JUSTJOIN

events:
  meetup:
    groups:
      - warsawjs
      - pykonik
      - wrocnet

ingest:
  scheduler:
    enabled: true
    initial-delay: PT3M
    fixed-delay: PT12H
    sources:
      - source: JUSTJOIN
        sitemap: https://justjoin.it/sitemaps/active-jobs/part0.xml

logging:
  level:
    root: INFO
    com.milosz.podsiadly.backend.ingest.mq: DEBUG
    com.milosz.podsiadly.backend.ingest.parser: DEBUG
    com.milosz.podsiadly.backend.ingest.config: DEBUG
    org.springframework.amqp: INFO

app:
  frontend:
    url: ${FRONTEND_URL:https://careerhub-it.com}

  mailer:
    enabled: ${MAILER_ENABLED:true}
    exchange: mailer.exchange
    routing:
      send: mail.send
      retry1: mail.retry.1m
      retry5: mail.retry.5m
      retry30: mail.retry.30m
      dlq: mail.dlq
    queue:
      send: mail.send
      retry1: mail.retry.1m
      retry5: mail.retry.5m
      retry30: mail.retry.30m
      dlq: mail.dlq
    retry:
      after1: PT1M
      after5: PT5M
      after30: PT30M
    listener:
      prefetch: 5
      concurrency: 1

    aws:
      region: ${AWS_REGION:us-east-1}
      from: ${SES_FROM}

    rate-limit:
      verification:
        min-interval: PT1M
        max-per-day: 5
      reset:
        min-interval: PT1M
        max-per-day: 5